// client/src/screens/Home.svelte
<script lang="ts">
  import { game } from "../lib/game.svelte";

  let name = $state(localStorage.getItem("cambio_name") ?? "");
  let code = $state(
    new URLSearchParams(location.search).get("room")?.toUpperCase() ?? ""
  );

  const canCreate = $derived(name.trim().length > 0);
  const canJoin = $derived(canCreate && code.trim().length >= 4);

  function remember() {
    localStorage.setItem("cambio_name", name.trim());
  }
  function create() {
    if (!canCreate) return;
    remember();
    game.create(name.trim());
  }
  function join() {
    if (!canJoin) return;
    remember();
    game.join(code.trim(), name.trim());
  }
</script>

<main class="screen home">
  <div class="brand">
    <div class="brand-logo">🃏</div>
    <h1>Cambio</h1>
    <p class="tagline">Lowest hand wins. Trust your memory.</p>
  </div>

  <div class="panel">
    <label class="field">
      <span>Your name</span>
      <input
        bind:value={name}
        maxlength="16"
        placeholder="e.g. Abdee"
        autocomplete="off"
      />
    </label>

    <button class="btn btn-primary" disabled={!canCreate} onclick={create}>
      Create a room
    </button>

    <div class="divider"><span>or join</span></div>

    <label class="field">
      <span>Room code</span>
      <input
        class="code-input"
        bind:value={code}
        maxlength="4"
        placeholder="ABCD"
        autocomplete="off"
        autocapitalize="characters"
        oninput={(e) =>
          (code = (e.currentTarget as HTMLInputElement).value.toUpperCase())}
      />
    </label>
    <button class="btn" disabled={!canJoin} onclick={join}>Join room</button>
  </div>
</main>

// client/src/screens/Home.tsx
import { useEffect, useState } from "react";
import type { Game } from "../App";

export function Home({ game }: { game: Game }) {
  const [name, setName] = useState(
    () => localStorage.getItem("cambio_name") ?? ""
  );
  const [code, setCode] = useState("");
  const [busy, setBusy] = useState(false);

  // Prefill room code from a shared link (?room=ABCD).
  useEffect(() => {
    const url = new URL(location.href);
    const r = url.searchParams.get("room");
    if (r) setCode(r.toUpperCase());
  }, []);

  const saveName = () => localStorage.setItem("cambio_name", name.trim());

  const create = async () => {
    if (!name.trim()) return;
    saveName();
    setBusy(true);
    await game.actions.createRoom(name.trim());
    setBusy(false);
  };

  const join = async () => {
    if (!name.trim() || code.trim().length < 4) return;
    saveName();
    setBusy(true);
    await game.actions.joinRoom(code.trim(), name.trim());
    setBusy(false);
  };

  return (
    <div className="screen home">
      <div className="brand">
        <div className="brand-logo">🃏</div>
        <h1>Cambio</h1>
        <p className="tagline">Lowest hand wins. Trust your memory.</p>
      </div>

      <div className="card-panel">
        <label className="field">
          <span>Your name</span>
          <input
            value={name}
            maxLength={16}
            placeholder="e.g. Alex"
            onChange={(e) => setName(e.target.value)}
            autoComplete="off"
          />
        </label>

        <button
          className="btn btn-primary"
          disabled={busy || !name.trim()}
          onClick={create}
        >
          Create a room
        </button>

        <div className="divider"><span>or join</span></div>

        <label className="field">
          <span>Room code</span>
          <input
            value={code}
            maxLength={4}
            placeholder="ABCD"
            className="code-input"
            onChange={(e) => setCode(e.target.value.toUpperCase())}
            autoComplete="off"
            autoCapitalize="characters"
          />
        </label>
        <button
          className="btn"
          disabled={busy || !name.trim() || code.trim().length < 4}
          onClick={join}
        >
          Join room
        </button>
      </div>
    </div>
  );
}
