// client/src/screens/Lobby.tsx
import { useState } from "react";
import type { Game } from "../App";

export function Lobby({ game }: { game: Game }) {
  const { view, youId, actions } = game;
  const [copied, setCopied] = useState(false);
  if (!view) return null;

  const me = view.players.find((p) => p.id === youId);
  const isHost = !!me?.isHost;
  const shareUrl = `${location.origin}${location.pathname}?room=${view.roomCode}`;

  const share = async () => {
    const data = {
      title: "Cambio",
      text: `Join my Cambio game — room ${view.roomCode}`,
      url: shareUrl,
    };
    try {
      if (navigator.share) await navigator.share(data);
      else throw new Error("no share");
    } catch {
      await navigator.clipboard.writeText(shareUrl);
      setCopied(true);
      setTimeout(() => setCopied(false), 1500);
    }
  };

  return (
    <div className="screen lobby">
      <div className="lobby-head">
        <div className="room-code" onClick={share}>
          <span className="room-code-label">Room</span>
          <span className="room-code-value">{view.roomCode}</span>
        </div>
        <button className="btn btn-ghost" onClick={() => actions.leaveRoom()}>
          Leave
        </button>
      </div>

      <button className="btn btn-share" onClick={share}>
        {copied ? "Link copied!" : "📤 Share invite"}
      </button>

      <div className="players-list">
        <h2>Players ({view.players.length})</h2>
        {view.players.map((p) => (
          <div key={p.id} className="player-row">
            <span className="player-dot" data-on={p.connected} />
            <span className="player-name">
              {p.name}
              {p.id === youId && " (you)"}
            </span>
            {p.isHost && <span className="badge">Host</span>}
          </div>
        ))}
      </div>

      {isHost ? (
        <button
          className="btn btn-primary btn-lg"
          disabled={view.players.length < 2}
          onClick={() => actions.startGame()}
        >
          {view.players.length < 2 ? "Waiting for players…" : "Start game"}
        </button>
      ) : (
        <p className="hint">Waiting for the host to start…</p>
      )}
    </div>
  );
}

// client/src/screens/Lobby.svelte
<script lang="ts">
  import { game } from "../lib/game.svelte";

  let copied = $state(false);

  const view = $derived(game.view!);
  const shareUrl = $derived(
    `${location.origin}${location.pathname}?room=${view.roomCode}`
  );

  async function share() {
    const data = {
      title: "Cambio",
      text: `Join my Cambio game — room ${view.roomCode}`,
      url: shareUrl,
    };
    try {
      if (navigator.share) {
        await navigator.share(data);
        return;
      }
      throw new Error("no share");
    } catch {
      await navigator.clipboard.writeText(shareUrl);
      copied = true;
      setTimeout(() => (copied = false), 1500);
    }
  }
</script>

<main class="screen lobby">
  <div class="lobby-head">
    <div class="room-code">
      <span class="room-code-label">Room</span>
      <span class="room-code-value">{view.roomCode}</span>
    </div>
    <button class="btn btn-ghost" onclick={() => game.leave()}>Leave</button>
  </div>

  <button class="btn btn-share" onclick={share}>
    {copied ? "Link copied!" : "📤 Share invite"}
  </button>

  <div class="players">
    <h2>Players ({view.players.length}/2)</h2>
    {#each view.players as p (p.id)}
      <div class="player-row">
        <span class="player-dot" class:on={p.connected}></span>
        <span class="player-name">
          {p.name}{p.id === game.clientId ? " (you)" : ""}
        </span>
        {#if p.isHost}<span class="badge">Host</span>{/if}
      </div>
    {/each}
  </div>

  {#if game.isHost}
    <button
      class="btn btn-primary btn-lg"
      disabled={view.players.length < 2}
      onclick={() => game.send({ t: "start" })}
    >
      {view.players.length < 2 ? "Waiting for a player…" : "Start game"}
    </button>
  {:else}
    <p class="hint">Waiting for the host to start…</p>
  {/if}
</main>
