// client/src/lib/Card.svelte
<script lang="ts">
  import type { CardView } from "@cambio/shared";

  interface Props {
    card?: CardView | null;
    faceDown?: boolean;
    size?: "sm" | "md" | "lg";
    selectable?: boolean;
    selected?: boolean;
    highlight?: boolean;
    empty?: boolean;
    onclick?: () => void;
  }

  let {
    card = null,
    faceDown = false,
    size = "md",
    selectable = false,
    selected = false,
    highlight = false,
    empty = false,
    onclick,
  }: Props = $props();

  const SUIT: Record<string, string> = {
    hearts: "♥",
    diamonds: "♦",
    clubs: "♣",
    spades: "♠",
  };

  const faceUp = $derived(!!card?.faceUp && !faceDown);
  const red = $derived(card?.suit === "hearts" || card?.suit === "diamonds");
</script>

{#if empty || card === null}
  <div class="card card-{size} card-empty"></div>
{:else}
  <button
    type="button"
    class="card card-{size}"
    class:card-face={faceUp}
    class:card-back={!faceUp}
    class:card-red={red}
    class:card-selectable={selectable}
    class:card-selected={selected}
    class:card-highlight={highlight}
    disabled={!selectable && !onclick}
    {onclick}
  >
    {#if faceUp}
      <span class="card-rank">{card.rank}</span>
      <span class="card-suit">{SUIT[card.suit ?? "spades"]}</span>
    {:else}
      <span class="card-back-emblem">✦</span>
    {/if}
  </button>
{/if}

// client/src/components/Card.tsx
import type { CardView } from "@cambio/shared";

const SUIT_SYMBOL: Record<string, string> = {
  hearts: "♥",
  diamonds: "♦",
  clubs: "♣",
  spades: "♠",
};

interface CardProps {
  card?: CardView | null;
  /** Force showing the back even if data is present. */
  faceDown?: boolean;
  selectable?: boolean;
  selected?: boolean;
  highlight?: boolean;
  empty?: boolean;
  size?: "sm" | "md" | "lg";
  onClick?: () => void;
}

export function Card({
  card,
  faceDown,
  selectable,
  selected,
  highlight,
  empty,
  size = "md",
  onClick,
}: CardProps) {
  if (empty || card === null) {
    return <div className={`card card-${size} card-empty`} />;
  }

  const faceUp = !!card?.faceUp && !faceDown;
  const red = card?.suit === "hearts" || card?.suit === "diamonds";

  const classes = [
    "card",
    `card-${size}`,
    faceUp ? "card-face" : "card-back",
    red ? "card-red" : "card-black",
    selectable ? "card-selectable" : "",
    selected ? "card-selected" : "",
    highlight ? "card-highlight" : "",
  ]
    .filter(Boolean)
    .join(" ");

  return (
    <button
      type="button"
      className={classes}
      onClick={onClick}
      disabled={!selectable && !onClick}
    >
      {faceUp && card ? (
        <>
          <span className="card-rank">{card.rank}</span>
          <span className="card-suit">{SUIT_SYMBOL[card.suit ?? "spades"]}</span>
        </>
      ) : (
        <span className="card-back-emblem">🃏</span>
      )}
    </button>
  );
}
